version: "3"
services: 
  neo4j:
    image: proteomegraph
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "1337:1337"
      - "7687:7687"
    volumes:
      - ./logs:/logs
      - ./conf:/conf

  notebook:
    image: cbleker/jupyter-graph-notebook:latest
    ports:
      - "8888:8888"
    links:
      - neo4j:neo4j
    volumes:
      - ./examples:/home/jovyan/examples
      - ./work:/home/jovyan/work
      - ./data:/home/jovyan/data

